/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as DeepDiveRouteImport } from './routes/deep-dive'
import { Route as PropostaRouteImport } from './routes/proposta'
import { Route as ConhecimentoIndexRouteImport } from './routes/conhecimento.index'
import { Route as ConhecimentoModuloIdRouteImport } from './routes/conhecimento.$moduloId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepDiveRoute = DeepDiveRouteImport.update({
  id: '/deep-dive',
  path: '/deep-dive',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaRoute = PropostaRouteImport.update({
  id: '/proposta',
  path: '/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoIndexRoute = ConhecimentoIndexRouteImport.update({
  id: '/conhecimento/',
  path: '/conhecimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoModuloIdRoute = ConhecimentoModuloIdRouteImport.update({
  id: '/conhecimento/$moduloId',
  path: '/conhecimento/$moduloId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/deep-dive': typeof DeepDiveRoute
  '/proposta': typeof PropostaRoute
  '/conhecimento/$moduloId': typeof ConhecimentoModuloIdRoute
  '/conhecimento/': typeof ConhecimentoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/deep-dive': typeof DeepDiveRoute
  '/proposta': typeof PropostaRoute
  '/conhecimento/$moduloId': typeof ConhecimentoModuloIdRoute
  '/conhecimento': typeof ConhecimentoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/deep-dive': typeof DeepDiveRoute
  '/proposta': typeof PropostaRoute
  '/conhecimento/$moduloId': typeof ConhecimentoModuloIdRoute
  '/conhecimento/': typeof ConhecimentoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora'
    | '/deep-dive'
    | '/proposta'
    | '/conhecimento/$moduloId'
    | '/conhecimento/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora'
    | '/deep-dive'
    | '/proposta'
    | '/conhecimento/$moduloId'
    | '/conhecimento'
  id:
    | '__root__'
    | '/'
    | '/calculadora'
    | '/deep-dive'
    | '/proposta'
    | '/conhecimento/$moduloId'
    | '/conhecimento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraRoute: typeof CalculadoraRoute
  DeepDiveRoute: typeof DeepDiveRoute
  PropostaRoute: typeof PropostaRoute
  ConhecimentoModuloIdRoute: typeof ConhecimentoModuloIdRoute
  ConhecimentoIndexRoute: typeof ConhecimentoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-dive': {
      id: '/deep-dive'
      path: '/deep-dive'
      fullPath: '/deep-dive'
      preLoaderRoute: typeof DeepDiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta': {
      id: '/proposta'
      path: '/proposta'
      fullPath: '/proposta'
      preLoaderRoute: typeof PropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento/': {
      id: '/conhecimento/'
      path: '/conhecimento'
      fullPath: '/conhecimento/'
      preLoaderRoute: typeof ConhecimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento/$moduloId': {
      id: '/conhecimento/$moduloId'
      path: '/conhecimento/$moduloId'
      fullPath: '/conhecimento/$moduloId'
      preLoaderRoute: typeof ConhecimentoModuloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraRoute: CalculadoraRoute,
  DeepDiveRoute: DeepDiveRoute,
  PropostaRoute: PropostaRoute,
  ConhecimentoModuloIdRoute: ConhecimentoModuloIdRoute,
  ConhecimentoIndexRoute: ConhecimentoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
